App2/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.animal.urls', namespace='animal')),
    path('pessoa/', include('apps.pessoa.urls', namespace='pessoa')),
]

apps/animals/urls.py
from django.urls import path
from .views import (home, about, AnimalsCreateView, 
                   AnimalsListView, AnimalsDetailView, 
                   AnimalsUpdateView, AnimalsUpdateDetailView,
                   AnimalsDeleteView, AnimalsDeleteDetailView)

app_name = 'animals'

urlpatterns = [
    path('', home, name='home'), # Com espaço vazio é a pagina inicial
    path('about/', about, name='about'),
    path('novo/', AnimalsCreateView.as_view(), name='novo'),
    path('lista/', AnimalsListView.as_view(), name='lista'),
    path('detalhe/<int:pk>/', AnimalsDetailView.as_view(), name='detalhe'),
    path('atualizar/<int:pk>/', AnimalsUpdateView.as_view(), name='atualizar'),
    path('detalhe/atualizar/<int:pk>/', AnimalsUpdateDetailView.as_view(), name='detalhe-atualizar'),
    path('eliminar/confirmar/<int:pk>/', AnimalsDeleteView.as_view(), name='eliminar'),
    path('detalhe/eliminar/confirmar/<int:pk>/', AnimalsDeleteDetailView.as_view(), name='detalhe-eliminar'),
    path('detalhe/atualizar/<int:pk>/', AnimalsUpdateDetailView.as_view(), name='detalhe-eliminar'),
    path('atualizar/<int:pk>/', AnimalsUpdateView.as_view(), name='atualizar'),
    path('confirmar/elimihar/<int:pk>/', AnimalsDeleteView.as_view(), name='eliminar')
    
]

apps/animal/models.py
from django.db import models

# Create your models here.

apps/animals/models.py
from django.db import models

# Create your models here.
from django.db import models
from apps.pessoa.models import Pessoa

# Create your models here.
class Animals(models.Model):
    nome = models.CharField(max_length=50)
    especie = models.CharField(max_length=30)
    #idade = models.IntegerField(blank=True, null=True) # assim não tem nenhum valor
    #idade = models.IntegerField(default=0)# coloca idade automaticamente
    idade = models.IntegerField()
    pessoa = models.ForeignKey(Pessoa, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        #return self.nome
        #return f'{self.especie}: {self.nome} / idade: {self.idade} anos'
        return f'{self.especie}: {self.nome}'

apps/despesa/models.py
from django.db import models

# Create your models here.

apps/animal/views.py
from django.shortcuts import render

# Create your views here.

apps/animals/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Animals

# Apresentação de página estática
def home(request):
    return render(request, 'animals/home.html')

def about(request):
    return render(request, 'animals/about.html')
# Create your views here.
class AnimalsCreateView(CreateView):
    model = Animals # atributo
    fields = '__all__' # atributo que mostra Nome, Especie , Idade em Animal
    #success_url = reverse_lazy('animals:home')
    success_url = reverse_lazy('animals:lista')  

class AnimalsListView(ListView):
    model = Animals

class AnimalsDetailView(DetailView):
    model = Animals 

class AnimalsUpdateView(UpdateView):
    model = AnimalsListView
    fields = ['nome', 'idade', 'pessoa']
    template_name = 'animals/animals_update.html'
    success_url = reverse_lazy('animal:lista') 

class AnimalsUpdateDetailView(UpdateView):
    model = Animals
    fields = ['nome', 'idade', 'pessoa']
    template_name = 'animals/animals_detail_update.html'
    #success_url = reverse_lazy('animals:lista')
    
    def get_success_url(self):
        return reverse('animals:detalhe', kwargs={'pk': self.object.id})

class AnimalsDeleteView(DeleteView):
    model = Animals
    template_name = 'animals/animals_detail_confirm_delete.html'
    success_url = reverse_lazy('animals:lista')

class AnimalsDeleteDetailView(DeleteView):
    model = Animals
    template_name = 'animals/animals_detail_confirm_delete.html'
    success_url = reverse_lazy('animals:lista')

apps/despesa/views.py
from django.shortcuts import render

# Create your views here.

apps/pessoa/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from apps.pessoa.models import Pessoa

# Create your views here.
def contacts(request):
    return render(request, 'pessoa/contacts.html')

def about(request):
    return render(request, 'pessoa/about.html')

def email(request):
    return render(request, 'pessoa/email.html')    
# Create your views here.
class PessoaCreateView(CreateView):
    model = Pessoa 
    fields = '__all__'
    #success_url = reverse_lazy('pessoa:home')
    success_url = reverse_lazy('pessoa:lista')

class PessoaListView(ListView):
    model = Pessoa

class PessoaDetailView(DetailView):
    model = Pessoa 

class PessoaUpdateView(UpdateView):
    model = Pessoa 
    fields = ['nome', 'idade', 'email']
    template_name = 'pessoa/pessoa_update.html'
    success_url = reverse_lazy('pessoa:lista')

class PessoaUpdateDetailView(UpdateView):
    model = Pessoa 

class PessoaDeleteView(DeleteView):
    model = Pessoa 
    success_url = reverse_lazy('pessoa:lista')    

apps/animals/templates/animals/about.html
{% extends "base.html" %}

{% block content %}
<p>Sobre a nossa aplicação</p>
{% endblock %}

apps/animals/templates/animals/animal_detail_atualizar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <hr>
    <a class="btn btn-outline-primary" href="{% url 'animals:detalhe-atualizar' %}">Echo</a>
    <hr>
    <form method="Post">
        {% csrf_token %}
        {{ form|crispy}}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class="btn btn-outline-danger" href="{% url 'animals:lista' %}"><i class="fa-sharp fa-solid fa-backward"></i></a>
    </form>
</div>
{% endblock %}

apps/animals/templates/animals/animals_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section">
    <h3>Animals</h3>
    <hr>
    <form method="Post">
        {% csrf_token %}
        <p>Tem a certeza que pretende eliminar {{ object.especie }} {{ object.nome }}</p>
        {{ form }}
        <br>
        <button class="btn btn-outline-danger" type="submit">Sim</button>
        <a class="btn btn-outline-primary" href="{% url 'animals:lista' %}">Não</a>
    </form>
</div>
{% endblock %}

apps/animals/templates/animals/animals_detail.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
    <div class="row">
        <div class="col-4">
            <h3>Animal</h3>
        </div>
        <div class="col-3">
            <a class="btn btn-outline-primary" href="{% url 'animals:detalhe-atualizar' object.id %}"><i class="fa-solid fa-pencil"></i></a>
        </div>
        <div class="col-5">
            <a class="btn btn-outline-danger" href="{% url 'animals:detalhe-eliminar' object.id %}"><i class="fa-solid fa-trash-can"></i></a>
        </div>
    </div>
    <hr>
    <!--<div style="padding: 15px;">-->
    <div>
        <p><b>Nome: </b>{{object.nome}}</p>
        <p><b>Espécie: </b>{{object.especie}}</p>
        <p><b>Idade: </b>{{object.idade}}</p>
    </div>
    <a class="btn btn-outline-danger" href="{% url 'animals:lista' %}"><i class="fa-sharp fa-solid fa-backward"></i></i></a>
    <hr>
</div>
{% endblock %}

apps/animals/templates/animals/animals_detail_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <h3>Animals</h3>
    <hr>
    <form method="Post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12 col-md-4">
              {{ form.nome|as_crispy_field }}
            </div>
            <div class="col-12 col-md-4">
                {{ form.idade|as_crispy_field }}
            </div>
            <div class="col-12 col-md-4">
                {{ form.pessoa|as_crispy_field }}
            </div>
        </div>{{ form|crispy}}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class="btn btn-outline-danger" href="{% url 'animals:detalhe' object.id %}"><i class="fa-sharp fa-solid fa-backward"></i></a>
    </form>
</div>
{% endblock %}

apps/animals/templates/animals/animals_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <h3>Animal</h3>
    <hr>
    <form method="Post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12 col-md-3">
              {{ form.nome|as_crispy_field }}
            </div>
            <div class="col-12 col-md-3">
                {{ form.nome|as_crispy_field }}
            </div>
        </div>
        {{ form|crispy}}
        <br>
        <button class="btn btn-outline-primary" type="submit">Criar</button>
        <a class="btn btn-outline-danger" href="{% url 'animals:lista' %}"><i class="fa-sharp fa-solid fa-backward"></i></a>
    </form>
</div>
{% endblock %}

apps/animals/templates/animals/animals_list.html
{% extends "base.html" %}

{% block content %}

<h4>novo <a class="btn btn-primary" href="{% url 'animals:novo' %}"><i class="fa-solid fa-plus"></i></a></h4>

<table class="table">
    <h3>Animals</h3>
    <hr>
<tr>
    <th>Nome</th>
    <th>Espécie</th>
    <th>Idade</th>
    <th>Ver</th>
    <th>Editar</th>    
    <th>Excluir</th>
</tr>
{% for object in object_list %}
<tr>
    <td>{{ object.nome }}</td>
    <td>{{ object.especie }}</td>
    <td>{{ object.idade }}</td>
    <td><a class="btn btn-outline-primary" href="{% url 'animals:detalhe' object.id %}"><i class="fa-solid fa-eye"></i></a></td>
    <td><a class="btn btn-outline-primary" href="{% url 'animals:atualizar' object.id %}"><i class="fa-solid fa-pencil"></td>
    <td><a class="btn btn-outline-danger" href="{% url 'animals:eliminar' object.id %}"><i class="fa-solid fa-trash-can"></td>
</tr>
<!-- <p>{{ object.nome }}</p>
<p>{{ object.especie }}</p>
<p>{{ object.idade }}</p> -->

{% endfor %}
</table>
{% endblock %}

apps/animals/templates/animals/animals_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <h3>Animals</h3>
    <hr>
    <form method="Post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12 col-md-4">
              {{ form.nome|as_crispy_field }}
            </div>
            <div class="col-12 col-md-4">
                {{ form.idade|as_crispy_field }}
            </div>
            <div class="col-12 col-md-4">
                {{ form.pessoa|as_crispy_field }}
            </div>
        </div>
        {{ form|crispy}}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class="btn btn-outline-danger" href="{% url 'animals:lista' %}"><i class="fa-sharp fa-solid fa-backward"></i></a>
    </form>
</div>
{% endblock %}

apps/animals/templates/animals/contacts.html
{% extends "base.html" %}

{% block content %}
<p>Nosso contacto</p>
{% endblock %}

templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/66c0c9e89a.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="../templates/css/base.css">
    </head>
    <style>
        /* .container {
            margin-left: 350px;
            margin-top: 80px;
            width: 180px;
            height: 100px;
            padding: 15px;
            background-color: rgb(29, 166, 235);           
        } */
    </style> 
    <body>
      <nav class="navbar navbar-expand-sm" style="background-color: #0c2aec;">
        <div class="container-fluid">
            <a class="navbar-brand mb-0 h1" href="#">Tarefas Navbar</a>
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link active" href="{% url 'animal:home' %}" style="color: White;">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link active" href="{% url 'animal:about' %}" style="color: White;">About</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link active" href="{% url 'animal:lista' %}" style="color: White;">Animais</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link active" href="{% url 'pessoa:lista' %}" style="color: White;">Pessoas</a>
              </li>  
              <!-- <li class="nav-item active">
                <a class="nav-link active" href="{% url 'despesa:lista' %}" style="color: White;">Despesas</a>
              </li>             -->
              <li class="nav-item active">
                <a class="nav-link active" href="{% url 'pessoa:contacts' %}" style="color: White;">Contacts</a>
              </li>
            </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder=" " aria-label="Search">
            <button class="btn btn-outline-success" type="submit" style="color: White;">Search</button>
          </form>
        </div>
      </nav>
       <div style="padding-top: 20px;" class="container">
        <!-- <h1>C.R.U.D.</h1><br> <h4>10/2022</h4> -->
        {% block content %}{% endblock %} 
        <a href="https://getbootstrap.com/docs/5.2/getting-started/introduction/">Link Aprendizagem</Link></a><br><br>
      </div>
      
      

          
                    <!--{% load static %}
          <img src="{% static 'media/imagens/shark.jpg' %}" alt="My image"><h4>shark teeth Miocenic</h4>>
          <img src="../Beta/App2/static/media/imagens/shark teeth Miocenic.jpg"><h4>shark teeth Miocenic</h4>
          <p>Found in Adiça beach area, Portugal 09-2021</p>
          <img src="../Beta/apps/pessoa/media/imagens/2 shark teeths Miocenic.jpg"><h4>2 shark teeths Miocenic</h4>
          <p>It's brown found in Costa Caparica beach area, Portugal 07-2021</p-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
          <!--a href="https://www.google.com/search?q=Shark+fossil&tbm=isch&ved=
          2ahUKEwiD5r7u1-v1AhUu2uAKHevuARQQ2-cCegQIABAA&oq=Shark+fossil&gs_lcp=
          CgNpbWcQDDIECAAQEzIECAAQEzIECAAQEzIECAAQEzIECAAQEzIECAAQEzIECAAQEzIEC
          AAQEzIECAAQEzIICAAQBxAeEBM6BwgjEO8DECdQiBdYiBdg_C9oAHAAeACAAViIAaEBkg
          EBMpgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=ohAAYoOND660gwfr3Ye
          gAQ&bih=694&biw=854&rlz=1C1CHZN_pt-PTPT991PT991" 
          target="_blank">Link Externo Shark Fossils</Link></a><br><br-->


          <!--p style="margin-left:550px;"><a href="retrieve">Login</a></p-->
    </body>
  
</html>